// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhPFYAeHmQiXDgZVHQF8MhqZq0HGwiR3U',
    appId: '1:270877871163:web:78e1befd4d103a5db5e01e',
    messagingSenderId: '270877871163',
    projectId: 'flash-chat-2974e',
    authDomain: 'flash-chat-2974e.firebaseapp.com',
    storageBucket: 'flash-chat-2974e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLje7LqSq35u93_2XSRMLwjTwVQn92R4',
    appId: '1:270877871163:android:f8c961d3888bc5d7b5e01e',
    messagingSenderId: '270877871163',
    projectId: 'flash-chat-2974e',
    storageBucket: 'flash-chat-2974e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkb_28792nvoRK99Fy7SQ_up8ov2Yk54',
    appId: '1:270877871163:ios:dd2ffc44c7eba154b5e01e',
    messagingSenderId: '270877871163',
    projectId: 'flash-chat-2974e',
    storageBucket: 'flash-chat-2974e.appspot.com',
    iosClientId: '270877871163-92d8aq2qbehhr1rjel6u7b380hc9epci.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchatAppFlutterCourse',
  );
}
